[package]
name = "eldritch"
version = "0.1.0"
edition = "2021"

[dependencies]
starlark = "0.6.0"
tempfile = "3.3.0"
anyhow = "1.0.55"
derive_more = "0.99.17"
sha256 = "1.0.3"
regex = "1.5.5"
reqwest = { version = "0.11.0" , features = ["blocking"] }
httptest = "0.15.4"
tokio = { version = "1.19.1" , features = ["macros"] }