#
# ============= DO NOT MANUALLY COMPILE =======================
# The reflective loader gets automatically compiled
# By the eldritch `build.rs` file. There's some differences
# in how to build the loader with `gnu` and `msvc`. If you're
# curious check out `realm/implants/lib/eldritch/build.rs`
#

[package]
name = "reflective_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[profile.dev]
opt-level = "z"   # This reduces the numebr of symbols not found.
lto = true
codegen-units = 1
panic = "abort"

[profile.release]
strip = true      # Automatically strip symbols from the binary.
opt-level = "z"   # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
ntapi = "0.4.1"

[dev-dependencies]
tempfile = "3.3.0"
object = "0.31.1"
anyhow = "1.0.65"

[dependencies.windows-sys]
version = "0.45.0"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_WindowsProgramming",
]
